server:
  port: 8300

spring:
  elasticsearch:
    rest:
      uris: 119.45.207.135:9200
  application:
    name: search-server

#配置负载
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 10000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 2 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 # 熔断超时时长：6000ms
# eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/